kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  namespace: "exerciselabs"
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard-us-east-1e"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
